"""Letter -> HandPose, backed by hand/poses.json (ARCHITECTURE.md §4.2).

hand/poses.json is generated by scripts/build_poses.py and is the single pose
source of truth (CLAUDE.md rule 4); this module only reads it.
"""
from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict, Mapping, Optional, Set, Tuple

from .types import HandPose

log = logging.getLogger(__name__)

DEFAULT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "poses.json")
MOTION_LETTERS = frozenset("JZ")


class PoseLibrary:
    """Named hand poses: the letters A-Z plus REST and OPEN.

    J and Z are motion letters. Their entries hold only the static handshape
    (the I shape for J, an index point for Z) until the stage-5 sequence model;
    pose_for() returns it and logs once per letter that the motion is skipped
    (ARCHITECTURE.md §7).
    """

    def __init__(self, poses: Mapping[str, HandPose], info: Optional[Mapping[str, Mapping[str, Any]]] = None,
                 meta: Optional[Mapping[str, Any]] = None):
        self._poses = {name.upper(): pose for name, pose in poses.items()}
        self._info = {name.upper(): dict(v) for name, v in (info or {}).items()}
        self.meta: Dict[str, Any] = dict(meta or {})
        self._motion_logged: Set[str] = set()

    @classmethod
    def load(cls, path: str = DEFAULT_PATH) -> "PoseLibrary":
        with open(path) as f:
            doc = json.load(f)
        entries = doc["poses"]
        poses = {name: HandPose.from_dict(entry) for name, entry in entries.items()}
        meta = {k: v for k, v in doc.items() if k != "poses"}
        return cls(poses, info=entries, meta=meta)

    @property
    def names(self) -> Tuple[str, ...]:
        return tuple(sorted(self._poses))

    @property
    def letters(self) -> Tuple[str, ...]:
        return tuple(n for n in self.names if len(n) == 1)

    @property
    def dataset_sha256(self) -> Optional[str]:
        return self.meta.get("dataset", {}).get("sha256")

    def __contains__(self, name: object) -> bool:
        return isinstance(name, str) and name.upper() in self._poses

    def __len__(self) -> int:
        return len(self._poses)

    def pose_for(self, name: str) -> HandPose:
        """The pose for a letter (any case) or a named pose such as REST or OPEN."""
        key = name.upper()
        if key not in self._poses:
            raise KeyError(f"no pose named {name!r}; known: {', '.join(self.names)}")
        if key in MOTION_LETTERS and key not in self._motion_logged:
            self._motion_logged.add(key)
            log.info("%s is a motion letter; showing its static handshape only", key)
        return self._poses[key]

    def info(self, name: str) -> Dict[str, Any]:
        """Where a pose came from: source, overridden fields, reason, motion note."""
        entry = self._info.get(name.upper(), {})
        return {k: v for k, v in entry.items() if k not in ("curl", "thumb_flex", "thumb_opp", "spread", "wrist_roll")}

    @property
    def rest(self) -> HandPose:
        return self.pose_for("REST")

    @property
    def open(self) -> HandPose:
        return self.pose_for("OPEN")
