"""Letter -> HandPose lookup backed by hand/poses.json (ARCHITECTURE.md §4.2).

hand/poses.json is the single pose source of truth (CLAUDE.md rule 4); it is
generated by scripts/build_poses.py and never edited by hand.

Implemented in ROADMAP stage 2.
"""
